"""
timeline_vm.py — Workflow state history → timeline rows.

Rows are generated by iterating the ``WorkflowStatus`` enum, never a hardcoded
list. ``GUARDRAILS_FAILED`` already has a legal edge to ``TERMINATED`` in
``VALID_TRANSITIONS``; it is unreachable only because ``orchestrator.py:59``
hardcodes ``sm.transition(GUARDRAILS_PASSED)``. The day ``src/guardrails/``
ships, that state goes live — and a timeline built from the enum already knows.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, Optional

from src.config.constants import WorkflowStatus

#: Row states
DONE = "done"
CURRENT = "current"
PENDING = "pending"
UNKNOWN = "unknown"


def all_states() -> list[WorkflowStatus]:
    """Every WorkflowStatus, in declaration order."""
    return list(WorkflowStatus)


def timeline_rows(history: Optional[Sequence[WorkflowStatus]]) -> list[dict[str, Any]]:
    """Build one row per WorkflowStatus.

    ``history=None`` means the state history is unavailable — which is the case
    for every running workflow today, because ``orchestrator.run()`` holds its
    ``WorkflowStateMachine`` in a local variable and never writes ``ctx.status``
    (BLOCKER-1). Rows come back marked UNKNOWN and ``available=False`` so the
    view can say so instead of drawing a fake timeline.
    """
    available = history is not None
    seen = set(history or ())
    current = history[-1] if history else None

    rows: list[dict[str, Any]] = []
    for status in all_states():
        if not available:
            state = UNKNOWN
        elif status == current:
            state = CURRENT
        elif status in seen:
            state = DONE
        else:
            state = PENDING

        rows.append(
            {
                "status": status.value,
                "state": state,
                "available": available,
            }
        )
    return rows


def timeline_unavailable_reason() -> str:
    """Why the timeline is empty. Shown verbatim; do not paper over it."""
    return (
        "Workflow state is not observable: the orchestrator never writes "
        "ctx.status and keeps its state machine as a local variable (BLOCKER-1)."
    )
